"""
Django settings for backendpandacar project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-nad2nz^fsmf^+vcd=l9k5&&wj@3dcuu5@axa2fls3##pwa1p8^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'api',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders'
]

MIDDLEWARE = [
     "corsheaders.middleware.CorsMiddleware", 
    "django.middleware.common.CommonMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1'
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'backendpandacar.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backendpandacar.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#media for photos
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

from datetime import timedelta

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'backendpandacar.custom_classes.CustomAuthentication'
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
        'rest_framework.throttling.ScopedRateThrottle'
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/min',  #anonymous user limit
        'user': '50/min',  #user limit
        'custom_login': '20/min',  #login endpoint limit 
        'custom_cars': '10/min',  #get_cars endpoint limit
        'custom_availability': '10/min', #get_availability endpoint limit
        'custom_users': '10/min',  #get_users endpoint limit
        'custom_add_to_favorites': '20/min',#add_to_favorites ednpoint limit
        'custom_add_to_cart': '10/min',#add_to_cart ednpoint limit
        'custom_get_to_favorites': '20/min',#get_to_favorites ednpoint limit
        'custom_get_cart': '10/min',#get_cart ednpoint limit
    },


}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),  
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'BLACKLIST_AFTER_ROTATION': True,

    "AUTH_COOKIE": "access_token",  
    "AUTH_COOKIE_DOMAIN": "localhost",  
    "AUTH_COOKIE_SECURE": False,  
    "AUTH_COOKIE_HTTP_ONLY": True,  
    "AUTH_COOKIE_PATH": "/",  
    "AUTH_COOKIE_SAMESITE": None,

    "AUTH_COOKIE_REFRESH_TOKEN": "refresh_token",  
    "AUTH_COOKIE_REFRESH_TOKEN_DOMAIN": "localhost",
    "AUTH_COOKIE_REFRESH_TOKEN_SECURE": False,  
    "AUTH_COOKIE_REFRESH_TOKEN_HTTP_ONLY": True,  
    "AUTH_COOKIE_REFRESH_TOKEN_PATH": "/",  
    "AUTH_COOKIE_REFRESH_TOKEN_SAMESITE": None, 
}

SIMPLE_JWT["TOKEN_BLACKLIST"] = True



AUTH_USER_MODEL = 'api.User'


# we work for the moment only with http, no https redirection

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173", 
    'http://127.0.0.1' 
]

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SAMESITE = 'None'
SESSION_COOKIE_SECURE = False  
CSRF_COOKIE_SECURE = False    
CSRF_COOKIE_HTTPONLY = True  
CSRF_COOKIE_SAMESITE = 'None'